### ISSUE TITLE
Build is failing 

### ISSUE THREAD

**Issue by zelima** [datahq/datahub-client#12]
Current build is failing cause of this test case https://github.com/datahq/datahub-client/blob/master/test/validate.test.js#L115

## Acceptance Criteria

* [x] Build is fine

## Tasks

* [x] take a look at tests and understand what's wrong
* [x] fix

**Comment by Mikanebu** [comment]
FIXED, updated schema for `data-package`, since there were changes on https://github.com/frictionlessdata/specs/commit/680f83b3a3cfe3b5d56d5896ddb5f86dcbefb4d9
