### ISSUE TITLE
[CAT] allow to pass sheet name or number 

### ISSUE THREAD

**Issue by zelima** [datahq/datahub-client#8]
As a wrangler, I want to specify the sheet number or name for `xls(x)` files and be able to view the data form that specific sheet. 

Currently, Think I can only view the first sheet. 

## Acceptance Criteria

* [x] able to perform run `data cat --format=xls --sheet=2 (or sheet naem) http://api.worldbank.org/v2/en/indicator/EN.ATM.CO2E.PC?downloadformat=excel | less`

**Comment by anuveyatsu** [comment]
This issue is a part of https://github.com/datahq/data-cli/issues/217

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datahq/datahub-client/pull/27
